### PR TITLE
Auth: factor auth routines + JWT

### PR DESCRIPTION
**Pull request by le-jeu**
**Build** [artifacts/pr307/wasabee.user.js](https://github.com/wasabee-project/Wasabee-IITC/raw/artifacts/pr307/wasabee.user.js)

### CODE REVIEW

**Comment by cloudkucooland** [comment]
works on iOS configurations which previously failed. Still some issues on my iPhone (which worked before) but this is an improvement over what we had.

**Comment by le-jeu** [comment]
Pairs with https://github.com/wasabee-project/Wasabee-CDN/blob/master/iitcplugin/firebase/index.html

**Comment by cloudkucooland** [comment]
I've been using it exclusively for weeks. No issues.

**Comment by le-jeu** [comment]
What about firebase, does notifications works from scratch ? going to https://cdn2.wasabee.rocks/iitcplugin/firebase/ and pressing the button may be needed, and if it's the case, I need some UI to make the user does this step.
This can be hidden if the firebase iframe is hosted on the same domain as the webui, using the same permission for both clients (but that also need a stable domain)

**Pull request merged**
