### PR TITLE
Change donate link

### PR DESCRIPTION
**Pull request by TheMitch2**
https://www.patreon.com/wasabee

### CODE REVIEW

**Comment by le-jeu** [comment]
this is already merged in `dev` by #299

**Comment by TheMitch2** [comment]
This is intended for the master branch. The old donation link is gone.

**Comment by le-jeu** [comment]
`dev` will be merged in `master` for next release, there is no need to merge this in directly on `master`

**Comment by TheMitch2** [comment]
Right now the donate link is incorrect. This needs to be added to prod.

**Pull request merged**
