### PR TITLE
Color picker close to its button on Chrome

### LINKED ISSUE #224: Link color dialog hiding in the corner
When clicking a link and attempting to change the color, the color selection box opens in the upper left hand corner while the link dialog appears centered on the click event. Moving this closer to the link dialog would make the feature more obvious and useful to new users of the feature.

### PR DESCRIPTION
**Pull request by le-jeu**
Makes chrome show the color picker close to its attached html element.
fix #224 (chrome only afaik)

Side effect: I dropped the pending work on touch event and clean the html event that interfers with the color picker (`click` event and stopPropagation/preventDefault).

### CODE REVIEW

**Comment by cloudkucooland** [comment]
Yes. The touch work will require someone who has a passion for it, or already knows it. I just gave up on trying to make it work properly.

**Comment by le-jeu** [comment]
I don't understand what it is the purpose of this work now. What doesn't work correctly or should be improved?

**Comment by TheMitch2** [comment]
Currently the color picker is in the upper left corner and it should be closer to the link dialog.
image

**Comment by le-jeu** [comment]
@TheMitch2  I meant the "touch" work

**Comment by cloudkucooland** [comment]
> I don't understand what it is the purpose of this work now. What doesn't work correctly or should be improved?

The buttons were wonky on touch devices. I was trying to find a way of making them better. This work setting aside the using click events in favor of using the full touch event framework. It was never any good. Other work made the buttons acceptable using clicks, making all this stuff unnecessary.

**Comment by cloudkucooland** [comment]
is this ready to merge?

**Review by cloudkucooland — APPROVED** [review]
looks good.

**Pull request merged**
